"""Add handler_code to api_config

Revision ID: 5351ccd7017b
Revises: e277732747ff
Create Date: 2026-01-27 21:25:32.587940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5351ccd7017b'
down_revision = 'e277732747ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('base_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('rate_limit')
        batch_op.drop_column('provider')
        batch_op.drop_column('request_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('rate_limit', sa.INTEGER(), nullable=True))
        batch_op.alter_column('base_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
