"""Add handler_code to api_configs

Revision ID: e277732747ff
Revises: 
Create Date: 2026-01-27 20:05:27.762320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e277732747ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('request_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('request_headers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('request_body_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_extract', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('process_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('handler_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_configs', schema=None) as batch_op:
        batch_op.drop_column('handler_code')
        batch_op.drop_column('process_code')
        batch_op.drop_column('response_extract')
        batch_op.drop_column('request_body_template')
        batch_op.drop_column('request_headers')
        batch_op.drop_column('request_path')
        batch_op.drop_column('request_method')

    # ### end Alembic commands ###
